import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { getSession } from "@/lib/server-utils";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Profile } from "@/components/profile";
//...existing code...

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {session?.id && <Profile />}

          {children}
        </ThemeProvider>
        {session?.id && (
          <Link href={"/create"} className="fixed bottom-20 right-20">
            <Button className="text-3xl p-2 text-center">+</Button>
          </Link>
        )}
      </body>
    </html>
  );
}
